org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

## Environment
mcversion=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoversion=21.1.240
neo_version_range=[21.1.0,)
loader_version=[4,)
parchment_minecraft=1.21.1
parchment_mappings=2024.11.17

## Mod Information
author=NadienDev
group=nadiendev.ultimatetransport
modid=ultimatetransport
mod_name=UltimateTransportSystem
mod_named=Ultimate Transport System
mod_description=Cables, pipes, player tubes, facades and ten tiers of energy cells. One transport mod for energy, fluids, gases, items and players.
license=MIT
mod_version=1.0.0
tag_lanzador=NeoForge
issue_tracker=https://github.com/SrNadien/Ultimate-Transport-System/issues

## Mod Dependencies
jei_version=19.39.0.369
jade_version=15.10.5+neoforge
patchouli_version=1.21.1-93-neoforge
mekanism_version=1.21.1-10.7.19.85
fluxnetworks_file=6089446
arsnouveau_version=5.13.1
enderio_version=v8.2.11-beta
oreexcavation_file=6327284
camol_file=7976624
curios_version=9.5.1+1.21.1
geckolib_version=4.9.2
architectury_version=13.0.11+neoforge
ftblibrary_version=2101.1.35
ftbultimine_version=2101.1.15
ultimateavaritia_file=8750475
reavaritia_file=8498772
ae2_version=19.2.17
guideme_version=21.1.17
kubejs_version=2101.7.2-build.374
rhino_version=2101.2.8-build.91+Rhino-1.21
